---
# Upgrace CentOS to latest kernel, enable OverlayFS, and disable kdump

- name: Find kernel version
  command: uname -r
  changed_when: false
  register: kernel_version

- debug: msg="CentOS base image at {{ kernel_version.stdout }}"

# Upgrade/Update all packages to latest version
- name: Upgrade CentOS
  yum: >
    name=*
    state=latest

- name: Find kernel version
  command: uname -r
  changed_when: false
  register: kernel_version

- debug: msg="CentOS upgraded to {{ kernel_version.stdout }}"

# kdump's default config will not work on machines with less than 2GB memory.
# But machine memory is configurable at runtime.
# So just disable kdump (bonus: frees up active memory).
# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/s2-kdump-configuration-cli.html
# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Kernel_Crash_Dump_Guide/sect-kdump-config-cli.html
- name: Disable kdump
  service:
    name: kdump
    state: stopped
    enabled: no



