#!/bin/bash

USER=$1
HOST=$2

if [ -n $USER ] || [ -n $HOST ]; then
  echo "usage: ./put-my-keys <user> <target host>"
  echo
  echo "eg. $ ./put-my-keys admin 192.168.1.250"
fi

scp -o StrictHostKeyChecking=no ~/.ssh/id_rsa $USER@$HOST:/home/admin
scp -o StrictHostKeyChecking=no ~/.ssh/id_rsa.pub $USER@$HOST:/home/admin

ssh -o StrictHostKeyChecking=no $USER@$HOST "mv /home/admin/id_rsa /home/admin/.ssh/"
ssh -o StrictHostKeyChecking=no $USER@$HOST "mv /home/admin/id_rsa.pub /home/admin/.ssh/"
